### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Cthulhu-Admin** [IL2CPP-Toolkit/Core#2]
Hello
I've used the IL2CPP-Toolkit on the game Raid Shadow Legends. The output is a DLL , 3KB in size , without any exported functions. I assume something isn't working, or I completely misunderstand how to use this.

Is there a small guide somewhere that explains the steps I would take to use this and what I should expect as the result of each step?

Are there a few games that are known to work which I could use as a reliable test case to ensure it's not me who is making the mistake.

**Comment by dnchattan** [comment]
I've done a quick update of the documentation, hopefully it's clearer with that what is going wrong for you.  I suspect based on what you're seeing that you didn't include the `-i` argument to specify which types should be exported.

However, since you're trying to use this for RSL, I encourage you to check out [Raid Toolkit](https://github.com/raid-toolkit/raid-toolkit-sdk) which uses this library extensively and should at least be a good point of reference, or better yet- somewhere you can collaborate and contribute to the community-built tool :smile:
